### PR TITLE
existingSecret for users and configurable accessMode for Samba

### PR DESCRIPTION
**Pull request by mosanden**
#### What this PR does / why we need it:

* Enable usage of existingSecret for Samba users: It is now possible to define users separate from the chart, e.g. in a SealedSecret.

* Make accessMode for volumes configurable in Samba: For example hostPath PVs do not support ReadWriteMany.

#### Checklist

- [x] Chart Version bumped
- [x] `make docs lint` passes
- [x] Variables are documented in the values.yaml as required in [Helm-Docs](https://github.com/norwoodj/helm-docs#valuesyaml-metadata).
- [x] PR contains the label that identifies the chart, e.g. `chart/[chart]`
- [x] PR contains the label that identifies the type of change, which is one of
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`

### CODE REVIEW

**Comment by mosanden** [comment]
Hey there, this PR needs the labels `change` and `chart/samba` i guess but I don't understand how I can add them.

**Comment by ccremer** [comment]
Hi!
Thanks for the interest and PR!
The change overall looks good to me :)

In CI the linting is failing, looks like you forgot a small change. However, the unit test job might need some investigation. It's been a while since I worked on the charts, so we might skip that one, unless you find the error immediately :)

**Comment by mosanden** [comment]
Seems like I didn't generate the docs correctly.

**Review by ccremer — COMMENTED** [review]
I propose a slight change in the parameter, allowing more flexibility. Otherwise LGTM

**Comment by mosanden** [comment]
I like that idea. I'll check if it works.

**Comment by mosanden** [comment]
Seems to work!

**Comment by ccremer** [comment]
Perfect!
Thank you for your contribution and time :)

**Comment by mosanden** [comment]
Thank you!

**Pull request merged**
